# 推荐的权重为 1～10，必须为正整数（不能太大以免溢出）

- id: 0
  string: "确定喵？"
  chance: 1

- id: 1
  string: "蠢萝莉！"
  chance: 10

- id: 2
  string: "ばか，へんたい，うるさい！"
  chance: 5

- id: 3
  string: "变态！"
  chance: 5

- id: 4
  string: "笨"
  chance: 5

- id: 5
  string: "你怎么傻乎乎的"
  chance: 5

- id: 6
  string: "不够色！"
  chance: 2

- id: 7
  string: "（透你不如透自己）"
  chance: 1

- id: 8
  string: "坏人！"
  chance: 2

- id: 9
  string: "坏！"
  chance: 2

- id: 10
  string: "这么笨，可以骗回去随便使用"
  chance: 2

- id: 11
  string: "是不是傻呀"
  chance: 2

- id: 12
  string: "这么奇怪的要求，果然是变态呢"
  chance: 5

- id: 13
  string: "喵？（看笨蛋的眼神）"
  chance: 5

- id: 14
  string: "（嗅嗅）反正也没啥用，抓去炖了吧～"
  chance: 2

- id: 15
  string: "别碰本喵，笨蛋是会传染的"
  chance: 2

- id: 16
  string: "吓到本喵了，你赔！"
  chance: 1

- id: 17
  string: "一般（提胖次）"
  chance: 1

- id: 18
  string: "屑！"
  chance: 1

- id: 19
  string: "你怎地不上天？"
  chance: 1

- id: 20
  string: "走开走开"
  chance: 1

- id: 21
  string: "太……太下流惹！"
  chance: 5

- id: 22
  string: "这么变态真的有什么存在的必要喵？（踩）"
  chance: 5

- id: 23
  string: "（嫌弃）"
  chance: 5

- id: 24
  string: "你来幼喵园，指定没你好果子吃噢"
  chance: 2

- id: 25
  image: "？.jpg"
  chance: 2

- id: 26
  image: "？？.jpg"
  chance: 2

- id: 27
  image: "抱歉奇迹和魔法是要付费的.jpg"
  chance: 10

- id: 28
  image: "变态啊.jpg"
  chance: 5

- id: 29
  image: "蠢萝莉！.jpg"
  chance: 10

- id: 30
  image: "大变态.png"
  chance: 5

- id: 31
  image: "瞪大了年幼的双眼.jpg"
  chance: 2

- id: 32
  image: "诶呀，这样不好吧.jpg"
  chance: 2

- id: 33
  image: "看你那么傻，抱抱好了.jpg"
  chance: 2

- id: 34
  image: "来自萝莉怀疑的目光.jpg"
  chance: 2

- id: 35
  image: "没看出来你这么变态.jpg"
  chance: 5

- id: 36
  image: "脑子是个好东西 但你马上就没了.jpg"
  chance: 1

- id: 37
  image: "能不能像我一样成熟点.jpg"
  chance: 2

- id: 38
  image: "你蠢也不是你的错.jpg"
  chance: 2

- id: 39
  image: "你就冲吧 最后害的还是你自己.jpg"
  chance: 1

- id: 40
  image: "你怎么24小时都在发情 能不能像我一样 歇一个小时.jpg"
  chance: 1

- id: 41
  image: "你这话什么意思 我不喜欢 撤回去.jpg"
  chance: 1

- id: 42
  image: "你这家伙，怕是已经被色欲冲昏头脑啦.jpg"
  chance: 1

- id: 43
  image: "你这是什么态度！.jpg"
  chance: 1

- id: 44
  image: "你这样做小心怀孕啊！.jpg"
  chance: 1

- id: 45
  image: "善有善报 恶有恶报 你没有人抱.jpg"
  chance: 10

- id: 46
  image: "少来这套 你心中毫无B数 迟早把你炖了.jpg"
  chance: 2

- id: 47
  image: "什么！再说一次试试？.jpg"
  chance: 2

- id: 48
  image: "我觉得，该打你一顿.jpg"
  chance: 2

- id: 49
  image: "这又是你 搭讪女孩子的花招吗.png"
  chance: 2

- id: 50
  image: "这种事情绝对很奇怪啊.jpg"
  chance: 5

- id: 51
  image: "真变态啊.jpg"
  chance: 5

- id: 52
  string: "星睿！"
  chance: 1