# 需要重命名为 config.yaml 以生效
nickname:          # 昵称，首个显示在日志中
  - 喵喵   
  - 幼喵园
selfid: 1234567890 # Bot 账号
superusers:        # 亲妈账号
  - 114514
  - 1919810
commandprefix: /   # 指令前缀
path: /home/ubuntu/Go-CQHTTP/数据/ # 资源文件路径
websocket:                   # WebSocket
  url: ws://example.com:6700 # WebSocket 链接
  accesstoken: Example       # WebSocket 密钥
log:                  # 日志
  level: "trace"      # 日志等级（小写）
  path: "log/log.txt" # 日志路径
  maxsize:    10      # 文件大小限制，单位 MB
  maxbackups: 0       # 最大保留日志文件数量，设置为 0 可以无限保留。
  expire: -1          # 日志文件的过期天数，大于该天数前的日志文件会被清理。设置为 0 可以禁用。 
webui:                # WebUI 配置
  url: "127.0.0.1:3000" # WebUI 链接