- bookid: "536611" # 萝变的我绝不向死神小姐屈服
  groupid: &groupidee
  - 678829435 # 测试
  - 676248663 # 奶酪屋
  - 213528017 # 魔法少女支部小队
  - 613294880 # 猫咖
  recordurl: 
  updatetime: 

- bookid: "44042"  # 星星花园
  groupid: *groupidee
  recordurl: 
  updatetime: 

- bookid: "429385" # 转生机凯种女王的我与血族的她
  groupid: *groupidee
  recordurl: 
  updatetime: 

- bookid: "177292" # 伊世之忆
  groupid: &groupidtest
  - 678829435 # 测试
  recordurl: 
  updatetime: 

- bookid: "545076" # 卖房小可爱不想为爱负责
  groupid: &groupidtest
  recordurl: 
  updatetime: 

- bookid: "511348" # 你好！我能把你抱走吗？
  groupid: &groupidtest
  recordurl: 
  updatetime: 